context:
  version: "1.1.5"

package:
  name: tf-playwright-stealth
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/tf-playwright-stealth/tf_playwright_stealth-${{ version }}.tar.gz
    sha256: 28a01cf65beb340876fd77487cf46df27124fab291ec97c0c9ac61f783f40059

build:
  number: 0
  skip:
    - win
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - playwright-python >=1,<2
    - fake-http-header >=0.3.5,<0.4.0

tests:
  - python:
      imports:
        - playwright_stealth
      pip_check: true

about:
  homepage: https://www.agentql.com/
  summary: Makes playwright stealthy like a ninja!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
